### ISSUE TITLE
Texture model isn't opening

### ISSUE THREAD

**Issue by HaddadEB** [SlicerIGT/SlicerIGT#222] opened 2024-10-23 21:01 UTC
Hello, my name is Eric Haddad. I'm PhD student in Biology and having troubles running the Texture Model in SlicerIGT.
I open my obj and jpeg files for model and texture but when I go to the texture model this error appears.

  _File "C:/Users/bioladmin/Desktop/Slicer 5.6.2/slicer.org/Extensions-32448/SlicerIGT/lib/Slicer-5.6/qt-scripted-modules/TextureModel.py", line 68, in setup
    parametersFormLayout.addRow(_("Model: ", self.inputModelSelector))
TypeError: tr() takes 1 positional argument but 2 were given_

I don't know how to solve, I've tried everything.
It doesn't look like a problem with my models/files since it opens in other computers. I've tried updating and/or redownloading the extensions it didn't work.

Any tips?

**Comment by lassoan** [comment] 2024-10-23 21:24
Thanks for reporting, the issue is fixed now.

**Closed** 2024-10-23 21:24 UTC
